# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s = "Hi there Sam!"
m=s.split()
print(m)
['Hi', 'there', 'Sam!']

['Hi', 'there', 'Sam!']


['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print('The diameter of',planet,'is',diameter,'kilometers')


The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':
[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])


hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
array=np.arange(20,35,2)
print(array)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
arr=np.arange(0, 9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
import pandas as pd
info = [['Kedari', 'Violet'], ['Divya', 'Pink'], ['Tulasi', 'Green']]

dk = pd.DataFrame(info, columns=['Name', 'Favourite Colour'])
dk


Name Favourite Colour
0  Kedari           Violet
1   Divya             Pink
2  Tulasi            Green

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import datetime
import pandas as pd
test_date = datetime.datetime.strptime("01-7-2022", "%d-%m-%Y")
number_of_days=40
date_generated = pd.date_range(test_date, periods=number_of_days)
print(date_generated.strftime("%d-%m-%Y"))


Index(['01-07-2022', '02-07-2022', '03-07-2022', '04-07-2022', '05-07-2022',
       '06-07-2022', '07-07-2022', '08-07-2022', '09-07-2022', '10-07-2022',
       '11-07-2022', '12-07-2022', '13-07-2022', '14-07-2022', '15-07-2022',
       '16-07-2022', '17-07-2022', '18-07-2022', '19-07-2022', '20-07-2022',
       '21-07-2022', '22-07-2022', '23-07-2022', '24-07-2022', '25-07-2022',
       '26-07-2022', '27-07-2022', '28-07-2022', '29-07-2022', '30-07-2022',
       '31-07-2022', '01-08-2022', '02-08-2022', '03-08-2022', '04-08-2022',
       '05-08-2022', '06-08-2022', '07-08-2022', '08-08-2022', '09-08-2022'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
import pandas as pd
df = pd.DataFrame(lists, columns = ['Sno', 'Name','Age'])
print(df)

   Sno Name  Age
0    1  aaa   22
1    2  bbb   25
2    3  ccc   24
